######################################################################
# Automatically generated by qmake (2.01a) ? 5? 11 14:36:46 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sky.h
SOURCES += fsat.cpp
